# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
     stdlib: puppetlabs/stdlib
     concat: puppetlabs/concat
     systemd: camptocamp/systemd
  repositories:
    facts: git://github.com/puppetlabs/puppetlabs-facts.git
    puppet_agent: git://github.com/puppetlabs/puppetlabs-puppet_agent.git
    provision: git://github.com/puppetlabs/provision.git
