---
mock_with: ':rspec'
user: trepasi
secure: CS3X5AkNNdaIpIrz7ovGvdozyShShEc/f8qk0btc0ox4e2gXcEQUZSSCawwFFd83LYeFvmlbP3+HgenUfC5Dm6QBmhpgVuhu1vjkPUHQvgwVb8Sb2rj1lyQsaE7cDN4bTmq0j+EYudc+Qj6EAhVQrHIZgBdS6jty4U6doGN2I17+/EHQpA0LCbb6V0+Ocm2pSQODzOEhFfJcCp0WNIShhuE8BdLSlVUV5Y4Ii6jZoIrbh7PIWMQsnRG3N0pv+T6j8816ahYftgWBIwj2IK6Su3//fuKYIKUPZhn2qe+EPQrhG0FA+CW3sW2ZnwcpuKVmpZTLaMDmMMl5yqbkcsWmYtj3I/QnNAR05DZ7yftzmO9mobdvx9pADX+fO4iuyRaklhCHrczxmyEIEiBRtzCQvAtT50fgrIMAwJDAzKH1uQGcSnj5xSoqs2K4USoXTqG0YmvutBoyGuI6rGx6Nez08JFIr9DesGZvtrRvKt0+Mh1Y1vIAYY6X6bpZvogeO4AavVvHjkJMC3wMGC1t+YEb4YTOYWiFgn2WNivOCumnVgTb+BX9DlxzuJtDiDjsGDibIHLnBlbFi9fNl75EulbK0dsEFUio+eVfopF/2QWrS/aKPuCUPJslIcWDrCm+Du1+WZoNCkmBQSdoHbTPq4QUGqhdYoxXzGlnoHw4FWWXTyg=
docker_sets:
  - set: debian-8
  - set: ubuntu-1604
