---
sudo: required
services:
  - docker
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
stages:
  - spec
  - beaker
  - deploy
matrix:
  fast_finish: true
  include:
    - stage: spec
      rvm: 2.4.2
      env: CHECK=rubocop
      bundler_args: --without system_tests
    - rvm: 2.4.2
      env: CHECK=release_checks
      bundler_args: --without system_tests
    - rvm: 2.1.9
      env: CHECK=spec PUPPET_GEM_VERSION="~> 4.0"
      bundler_args: --without system_tests
    - rvm: 2.4.1
      env: CHECK=spec PUPPET_GEM_VERSION="~> 5.0"
      bundler_args: --without system_tests
    - stage: beaker
      rvm: 2.4.2
      env: CHECK=beaker BEAKER_set=docker/debian-8 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
      run_opts: "--privileged"
    - rvm: 2.4.2
      env: CHECK=beaker BEAKER_set=docker/ubuntu-1604 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
      run_opts: "--privileged"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: trepasi
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
