---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
    - rvm: 2.4.2
      env: CHECK=rubocop
    - rvm: 2.4.2
      env: CHECK="syntax lint"
    - rvm: 2.4.2
      env: CHECK=metadata_lint
    - rvm: 2.4.2
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - rvm: 2.4.2
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1604
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - rvm: 2.4.2
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
