---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.2
      env: CHECK=rubocop
      bundler_args: --without system_tests
    - rvm: 2.4.1
      env: CHECK=release_checks
      bundler_args: --without system_tests
      # Spec with PE 2017.2.4
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="4.10.8" FACTER_GEM_VERSION="3.6.7" CHECK=spec
      bundler_args: --without system_tests
      # Spec with PE 2017.2.3
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="4.10.5" FACTER_GEM_VERSION="3.6.5" CHECK=spec
      bundler_args: --without system_tests
      # Spec with puppet-agent 5.1.0
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION="5.1.0" FACTER_GEM_VERSION="3.8.0" CHECK=spec
      bundler_args: --without system_tests
      # acceptance for Debian-8
    - rvm: 2.4.2
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
      script: bundle exec rake beaker
      services: docker
      sudo: required
      # acceptance for Ubuntu-16.04
    - rvm: 2.4.2
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1604
      script: bundle exec rake beaker
      services: docker
      sudo: required
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
